# Contains:
#   daily precipitation
# temperature
# long time spans
# Free and directly accessible.

# install.packages(c(
#   "rnoaa",
#   "tidyverse",
#   "lubridate",
#   "extRemes",
#   "evd",
#   "fitdistrplus",
#   "numDeriv"
# ))
# install.packages("remotes")
# remotes::install_github("ropensci/rnoaa")
library(rnoaa)
library(tidyverse)
library(lubridate)
library(extRemes)
library(evd)
#library(fitdistrplus)
library(numDeriv)
library(dplyr)
library(lubridate)
library(ggplot2)

data = read_csv("vignettes/real_data_application/crude_daily_10Y.csv")

# 2. Annual maxima --------
# Extreme-value theory usually works with block maxima.
annual_max <- data %>%
  mutate(date = mdy(date),
         year = year(date)) %>%
  group_by(year) %>%
  summarise(max_data = max(price, na.rm = TRUE)) %>%
  ungroup()

plot(
  annual_max$year,
  annual_max$max_data,
  type="b",
  pch=19,
  xlab="Year",
  ylab="Annual Maximum"
)

# Calculate monthly maximum per year
monthly_max <- data %>%
  mutate(
    date = mdy(date),
    year  = year(date),
    month = month(date, label = TRUE, abbr = TRUE) # Returns "Jan", "Feb", etc.
  ) %>%
  group_by(year, month) %>%
  summarise(max_data = max(price, na.rm = TRUE), .groups = "drop") %>%
  # Replace Inf/-Inf with NA if a month has only missing data
  mutate(max_data = ifelse(is.infinite(max_data), NA, max_data))

ggplot(monthly_max, aes(x = year, y = max_data, color = month, group = month)) +
  geom_line(linewidth = 0.8) +
  geom_point(size = 1.2, alpha = 0.6) +
  labs(
    title = "Annual Trend of Monthly Maximum",
    x = "Year",
    y = "Maximum (price)",
    color = "Month"
  ) +
  theme_minimal()


## Seasonal Trend line
# Define your station data (assuming 'data' data frame is already loaded for USW00014739)
# Filter for your specific station if your data frame contains multiple stations:
# data_cp <- data %>% filter(station == "USW00014739")

season_max <- data %>%
  mutate(
    date = mdy(date),
    year_raw = year(date),
    month_num = month(date),
    # Assign standard meteorological seasons
    season = case_when(
      month_num %in% c(12, 1, 2)  ~ "Winter",
      month_num %in% c(3, 4, 5)   ~ "Spring",
      month_num %in% c(6, 7, 8)   ~ "Summer",
      month_num %in% c(9, 10, 11) ~ "Autumn"
    ),
    # Shift December to belong to the next year's winter season
    # (e.g., Dec 1950 is part of the 1951 Winter season)
    year = if_else(month_num == 12, year_raw + 1, year_raw)
  ) %>%
  # Group by the seasonal year and the season name
  group_by(year, season) %>%
  summarise(max_data = max(price, na.rm = TRUE), .groups = "drop") %>%
  # Clean up -Inf values generated by max() on all-NA blocks
  mutate(max_data = ifelse(is.infinite(max_data), NA, max_data)) %>%
  # Ensure chronological order for the legend
  mutate(season = factor(season, levels = c("Winter", "Spring", "Summer", "Autumn")))

ggplot(season_max, aes(x = year, y = max_data, color = season, group = season)) +
  geom_line(linewidth = 1) +
  geom_point(size = 1.5, alpha = 0.7) +
  # Custom colors representing the seasons
  scale_color_manual(values = c("Winter" = "#2b8cbe", "Spring" = "#74c476", "Summer" = "#e34a33", "Autumn" = "#fe9929")) +
  labs(
    title = "Annual Trend of Seasonal Maximum datafall",
    subtitle = "Station: USW00014739 (Central Park, NY)",
    x = "Year (Winter adjusted to matching calendar year)",
    y = "Maximum Precipitation",
    color = "Season"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    legend.position = "bottom"
  ) + scale_x_continuous(n.breaks=10)


# 3. Extract records ---------

x <- monthly_max %>%  pull(max_data)
#x=x/max(x)

L <- rec_times(x)
R <- rec_values(x)

data_rec <- data.frame(
  rec_times = L,
  rec_values = R,
  time = length(x),
  year = monthly_max$year[L]
)

data_rec

## 4 - Exploratory Analysis ------
#Number of records.
# record trajectory
plot(
  L,
  R,
  type="b",
  pch=19,
  xlab="Record Time L_n",
  ylab="Record Value R_n"
)
# inter record times
waiting <- diff(L)

hist(
  waiting,
  breaks=10,
  main="Inter-record times",
  xlab="L_n - L_(n-1)"
)

# growth of records
plot(
  seq_along(R),
  R,
  type="b",
  pch=19,
  xlab="Record Number",
  ylab="Record Value"
)

## Model comparisons -----------
model_compare = matrix(0, 4, 4)
colnames(model_compare) = c("logLik", "AIC", "BIC", "Rank")

## 5A - fit likelihood -----------

lb_0 <- c(gamma = 1.01,
          location  = -100,
          scale = 0.01)

ub_0 <- c(gamma = 5,
          location = 100,
          scale = 1000)

x0_0 <- c(gamma = 1.1,
          location  = mean(x),
          scale = var(x))

logLikH0 = loglik_registry[["YNM"]][["all"]][["gumbel"]]

negLogLik_H0 <- function(params){

  -logLikH0(x, params)
}

fit_H0 <- NULL

for(iterations in 1:100){

  fit_H0 <- tryCatch(
    nlminb(
      start = x0_0,
      objective = negLogLik_H0,
      lower = lb_0,
      upper = ub_0
    ),
    error = function(e) NULL
  )

  if(!is.null(fit_H0) &&
     is.finite(fit_H0$objective) &&
     fit_H0$convergence == 0){

    break
  }

  x0_0 <- x0_0 + c(0.01, 0.01, 0.01)
}

if(is.null(fit_H0) || fit_H0$convergence != 0){
  next
}

param_H0_start <- c(
  fit_H0$par,
  logLik = -fit_H0$objective
)

param_H0_start
AIC_0 = - 2 * param_H0_start["logLik"] + 2 * length(fit_H0$par)
BIC_0 = - 2 * param_H0_start["logLik"] + log(121) * length(fit_H0$par)

model_compare[1,]=c(param_H0_start["logLik"], AIC_0, BIC_0, 0)
## 5B - fit likelihood under H1 -----------

lb_1 <- c(gamma = 1,
          location  = -100,
          scale = 0.01)

ub_1 <- c(gamma = 1,
          location = 100,
          scale = 100)

x0_1 <- c(gamma = 1,
          location  = mean(R),
          scale = sd(R))

logLikH1 =  loglik_registry[["iid"]][["all"]][["gumbel"]]
# Likelihood_under_H1 <- function(x, params){
#
#   logLikH1(
#     data   = data_rec,
#     params = params
#   )
# }

negLogLik_H1 <- function(params){

  -logLikH1(x, params)
}

fit_H1 <- NULL

for(iterations in 1:100){

  fit_H1 <- tryCatch(
    nlminb(
      start = x0_1,
      objective = negLogLik_H1,
      lower = lb_1,
      upper = ub_1
    ),
    error = function(e) NULL
  )

  if(!is.null(fit_H1) &&
     is.finite(fit_H1$objective) &&
     fit_H1$convergence == 0){

    break
  }

  x0_1 <- x0_1 + c(0.01, 0.01, 0.01)
}

if(is.null(fit_H1) || fit_H1$convergence != 0){
  next
}

param_H1_start <- c(
  fit_H1$par,
  logLik = -fit_H1$objective
)

param_H1_start
AIC_1 = - 2 * param_H1_start["logLik"] + 2 * length(fit_H1$par)
BIC_1 = - 2 * param_H1_start["logLik"] + log(121) * length(fit_H1$par)

model_compare[2,]=c(param_H1_start["logLik"], AIC_1, BIC_1, 0)
## 5C - fit likelihood under H2: DTRW-----------

lb_2 <- c(mean=0, sd = 0.01)

ub_2 <- c(mean=0,sd = 100)

x0_2 <- c(mean=0,sd = sd(x))

logLikH2 =  loglik_registry[["DTRW"]][["all"]][["norm"]]
# Likelihood_under_H2 <- function(x, params){
#
#   logLikH2(
#     data   = data_rec,
#     params = params
#   )
# }

negLogLik_H2 <- function(params){

  -logLikH2(x, params)
}

fit_H2 <- NULL

for(iterations in 1:100){

  fit_H2 <- tryCatch(
    nlminb(
      start = x0_2,
      objective = negLogLik_H2,
      lower = lb_2,
      upper = ub_2
    ),
    error = function(e) NULL
  )

  if(!is.null(fit_H2) &&
     is.finite(fit_H2$objective) &&
     fit_H2$convergence == 0){

    break
  }

  x0_2 <- x0_2 + c(0.01)
}

if(is.null(fit_H2) || fit_H2$convergence != 0){
  next
}

param_H2_start <- c(
  fit_H2$par,
  logLik = -fit_H2$objective
)

param_H2_start
AIC_2 = - 2 * param_H2_start["logLik"] + 2 * length(fit_H2$par)
BIC_2 = - 2 * param_H2_start["logLik"] + log(121) * length(fit_H2$par)

model_compare[3,]=c(param_H2_start["logLik"], AIC_2, BIC_2, 0)

## 5D - fit likelihood under H3: LDM-----------

lb_3 <- c(theta = 0.01,
          shape= 0.01,
          scale = 0.01)

ub_3 <- c(theta = 1,
          shape= 100,
          scale = 100)

x0_3 <- c(theta = 0.1,
          shape= (sd(x) / mean(x))^(-1.086),
          scale = sd(x))

logLikH3 =  loglik_registry[["LDM"]][["all"]][["weibull"]]

negLogLik_H3 <- function(params){

  -logLikH3(x, params)
}

fit_H3 <- NULL

for(iterations in 1:100){

  fit_H3 <- tryCatch(
    nlminb(
      start = x0_3,
      objective = negLogLik_H3,
      lower = lb_3,
      upper = ub_3
    ),
    error = function(e) NULL
  )

  if(!is.null(fit_H3) &&
     is.finite(fit_H3$objective) &&
     fit_H3$convergence == 0){

    break
  }

  x0_3 <- x0_3 + c(0.01, 0.01, 0.01)
}

if(is.null(fit_H3) || fit_H3$convergence != 0){
  next
}

param_H3_start <- c(
  fit_H3$par,
  logLik = -fit_H3$objective
)

param_H3_start
AIC_3 = - 2 * param_H3_start["logLik"] + 2 * length(fit_H3$par)
BIC_3 = - 2 * param_H3_start["logLik"] + log(121) * length(fit_H3$par)

model_compare[4,]=c(param_H3_start["logLik"], AIC_3, BIC_3, 0)

model_compare
# 6 uncertainity quantification ------
library(dplyr)
library(purrr)

# Define model metadata configurations
models_config <- list(
  list(id = "H0", loglik = logLikH0, pars = param_H0_start[c("gamma", "location", "scale")], names = c("gamma", "location", "scale")),
  list(id = "H1", loglik = logLikH1, pars = param_H1_start[c("location", "scale")], names = c("location", "scale")),
  list(id = "H2", loglik = logLikH2, pars = param_H2_start[c("mean","sd")], names = c("mean","sd")),
  list(id = "H3", loglik = logLikH3, pars = param_H3_start[c("theta", "shape", "scale")], names = c("theta", "shape", "scale"))
)

# Compute metrics dynamically using a map loop
all_models_df <- map_dfr(models_config, function(m) {

  # Compute Hessian and extract standard errors
  hess <- compute_hessian(m$loglik, data = x, par_vec = m$pars)
  se   <- sqrt(diag(hess$vcov))

  # Return structured dataframe per model
  data.frame(
    model         = m$id,
    parameter_idx = seq_along(m$pars),
    param_name    = m$names,
    estimate      = m$pars,
    std_error     = se,
    lower_ci      = m$pars - 1.96 * se,
    upper_ci      = m$pars + 1.96 * se,
    row.names     = NULL

  )
})

# View the final unified dataframe
print(all_models_df)

## 7 - parametric bootstrap for Critical Region -----
B <- 500

boot_est <- matrix(NA, B, 8)
colnames(boot_est) = c(names(param_H0_start), names(param_H2_start), "T" )
ratio = numeric(B)

for(b in 1:B){
  sim <- YNM_series(
    T     = nrow(monthly_max),
    dist  = "gumbel",
    gamma = param_H0_start["gamma"],
    location  = param_H0_start[["location"]],
    scale = param_H0_start[["scale"]]
  )

  ## Fit H0
  negLogLik_H0_sim <- function(params){

    -logLikH0(sim, params)
  }

  fit_H0_sim <- NULL

  for(iterations in 1:100){

    fit_H0_sim <- tryCatch(
      nlminb(
        start = x0_0,
        objective = negLogLik_H0_sim,
        lower = lb_0,
        upper = ub_0
      ),
      error = function(e) NULL
    )

    if(!is.null(fit_H0_sim) &&
       is.finite(fit_H0_sim$objective) &&
       fit_H0_sim$convergence == 0){

      break
    }

    x0_0 <- x0_0 + c(0.01, 0.01, 0.01)
  }

  if(is.null(fit_H0_sim) || fit_H0_sim$convergence != 0){
    next
  }

  # ## Fit H1
  # negLogLik_H1_sim <- function(params){
  #
  #   -logLikH1(data_rec_sim, params)
  # }
  # fit_H1_sim <- NULL
  #
  # for(iterations in 1:100){
  #
  #   fit_H1_sim <- tryCatch(
  #     nlminb(
  #       start = x0_1,
  #       objective = negLogLik_H1_sim,
  #       lower = lb_1,
  #       upper = ub_1
  #     ),
  #     error = function(e) NULL
  #   )
  #
  #   if(!is.null(fit_H1_sim) &&
  #      is.finite(fit_H1_sim$objective) &&
  #      fit_H1_sim$convergence == 0){
  #
  #     break
  #   }
  #
  #   x0_1 <- x0_1 + c(0.01, 0.01, 0.01)
  # }
  #
  # if(is.null(fit_H1_sim) || fit_H1_sim$convergence != 0){
  #   next
  # }

  ## Fit H2
  negLogLik_H2_sim <- function(params){

    -logLikH2(sim, params)
  }
  fit_H2_sim <- NULL

  for(iterations in 1:100){

    fit_H2_sim <- tryCatch(
      nlminb(
        start = x0_2,
        objective = negLogLik_H2_sim,
        lower = lb_2,
        upper = ub_2
      ),
      error = function(e) NULL
    )

    if(!is.null(fit_H2_sim) &&
       is.finite(fit_H2_sim$objective) &&
       fit_H2_sim$convergence == 0){

      break
    }

    x0_2 <- x0_2 + c(0, 0.01)
  }

  if(is.null(fit_H2_sim) || fit_H2_sim$convergence != 0){
    next
  }

  boot_est[b,] = c(fit_H0_sim$par, - fit_H0_sim$objective, fit_H2_sim$par, - fit_H2_sim$objective, length(sim))
  ratio[b] = -fit_H2_sim$objective -- fit_H0_sim$objective
}

lq = quantile(ratio, probs = 0.025)
uq = quantile(ratio, probs = 0.975)


cat("================== \n",
    "Observed LR: ", fit_H0$objective - fit_H2$objective,
    "\n Compared to critical region of [",lq,":",uq,"]",
    "\n================")
critical_region = data.frame(
  "H0_objective" = fit_H0$objective,
  "H1_objective" = fit_H2$objective,
  "LR" = fit_H0$objective - fit_H2$objective,
  "CR_lower_bound" = quantile(ratio, probs = 0.025),
  "CR_upper_bound" = quantile(ratio, probs = 0.975)

)
cat("================== \n",
    "Model Comparison",
    "\n================")
model_compare

cat("================== \n",
    "Estimation  Summary",
    "\n================")
all_models_df

sheets_list = list("parameters" = all_models_df,
                  "model_comparison" = model_compare,
                  "critical_region" = critical_region)

# 2. Save everything into one workbook
openxlsx::write.xlsx(sheets_list, file = paste0("vignettes/real_data_application/crude_oil_results_all.xlsx"))
